### ISSUE TITLE
CHECK_MESSAGE no longer works with DOCTEST_CONFIG_SUPER_FAST_ASSERTS

### ISSUE THREAD

**Issue by u3shit** [onqtam/doctest#280]
## Description
While updating doctest, CHECK_MESSAGE broke and it causes a compilation failure. It looks like it was broke in c494843840e007013e7951d9298b0bdd866568bd, it works in 2.1.0 while in 2.2.0 it fails with an error:
```
foo2.cpp:8:3: error: use of undeclared identifier 'DT_CHECK'
  CHECK_MESSAGE(x == 0, "Boo boo");
  ^
./doctest/doctest.h:2476:23: note: expanded from macro 'CHECK_MESSAGE'
#define CHECK_MESSAGE DOCTEST_CHECK_MESSAGE
                      ^
./doctest/doctest.h:2022:93: note: expanded from macro 'DOCTEST_CHECK_MESSAGE'
#define DOCTEST_CHECK_MESSAGE(cond, msg) do { DOCTEST_INFO(msg); DOCTEST_ASSERT_IMPLEMENT_2(DT_CHECK, cond); } while((void)0, 0)
                                                                                            ^
1 error generated.
```
I get the same error with 2.3.4.

### Steps to reproduce
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_SUPER_FAST_ASSERTS
#include <doctest/doctest.h>

TEST_CASE("x")
{
  int x = 2;
  CHECK_MESSAGE(x == 0, "Boo boo");
}
```
Compile with `clang++` without any special flags.

* doctest version: **v2.3.4**
* Operating System: **Gentoo Linux amd64**
* Compiler+version: **clang 8.0.1 (both with libc++ and gcc's libstdc++)**

**Comment by onqtam** [comment]
Thanks for reporting this regression!

fixed in the dev branch - you can use it from there immediately. I'll release 2.3.5 officially... at some point :)

**Comment by u3shit** [comment]
I can confirm that my sample is now working with the dev branch :+1:. I can't test it with my real code right now because of the two other bugs I've opened.
