### ISSUE TITLE
Can't compile with glibc master (future 2.34): SIGSTKSZ is no longer a constant

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [onqtam/doctest#473]
Hi,

I am trying to compile ccache (which embeds doctest as a third part library), using current glibc trunk (future glibc 2.34 to be released in 6 months). It fails with this error:

```
/workdir/src/ccache-4.2/src/third_party/doctest.h:4189:47: error: size of array 'altStackMem' is not an integral constant-expression
 4189 |         static char             altStackMem[4 * SIGSTKSZ];
```

Indeed if you look in latest NEWS file from glibc https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD:

```
  * Add _SC_MINSIGSTKSZ and _SC_SIGSTKSZ.  When _SC_SIGSTKSZ_SOURCE or
     _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ are no longer
     constant on Linux.  MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ)
     and SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ).
```

So would it be possible to update a bit the code to no longer rely on SIGSTKSZ being a constant ?

Cheers,
Romain

**Comment by dankamongmen** [comment]
I've got a PR that resolves this, so far as I can tell (was just coming here to file this bug). Opening a PR now.

**Comment by onqtam** [comment]
Cool, I'll wait for a PR to fix this :)

**Comment by dankamongmen** [comment]
oh, right, sorry. #474.

**Comment by jiridanek** [comment]
Hardcoding the stack size would be essentially a revert of https://github.com/onqtam/doctest/issues/129.

**Comment by dankamongmen** [comment]
> Hardcoding the stack size would be essentially a revert of #129.

I would disagree; we can keep the exact same static size. Or make it bigger. Those commits just added a factor to `SIGSTKSZ`.

Well, it can be dynamically allocated very early in the process lifetime, but I'm not familiar enough with doctest's innards to touch such fragile code (fragile because we're talking about POSIX alternate signal stacks and exceptional, fatal signals, not doctest's fault). There's also a portability concern; you're taking a broadly-available compile-time macro and bifurcating into a variety of system-specific, runtime discovery mechanisms (admittedly, everything else could just keep doing as it's doing).

AVX512 adds some pretty big registers, it is true, but surely there's some reasonable ceiling? [shrug] I'm all for discovering it at runtime, but that's an architectural decision for @onqtam imho; for now, we can at least keep building.

**Comment by onqtam** [comment]
Let's allocate the buffer. I'll do it if you guys tell me what ifdef to use to detect if `SIGSTKSZ` is no longer a constant, and what to use instead (and from which header). I'll release a new version of doctest after fixing this.

**Comment by onqtam** [comment]
just pushed a commit in the `dev` branch ( https://github.com/onqtam/doctest/commit/8ee91f37ba27397ef5eeedd2e542a4aaaa33ddc1 ) - let me know if it fixes the problem

**Comment by jiridanek** [comment]
@onqtam I fetched doctest.h from dev branch at https://github.com/onqtam/doctest/commit/17a07bd615aa9f16801f777074fb3f409bbc0260 and using it fixes my https://issues.apache.org/jira/browse/DISPATCH-1997 on Fedora Rawhide running on x86_64 (in Docker, but that should make no difference).

Works for me, thanks! I hope it will work on AVX512 just as well, @dankamongmen .

**Comment by onqtam** [comment]
It would be goot to test with a crashing example as well (to test the signal handler and alt stack) - something along the lines of
```c++
TEST_CASE("") {
    int* a = nullptr;
    CHECK((*a) == 5);
}
```

**Comment by jiridanek** [comment]
@onqtam Good catch, that crashed:

```
# /main/qpid-dispatch/build/tests/c_unittests/c_unittests
[doctest] doctest version is "2.4.5"
[doctest] run with "--help" for options
===============================================================================
/main/qpid-dispatch/tests/c_unittests/test_amqp.cpp:26:
TEST CASE:  

/main/qpid-dispatch/tests/c_unittests/test_amqp.cpp:26: FATAL ERROR: test case CRASHED: SIGSEGV - Segmentation violation signal

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 3 skipped
[doctest] assertions: 0 | 0 passed | 0 failed |
[doctest] Status: FAILURE!
Segmentation fault (core dumped)
```

I'm installing gdb to get a stacktrace. I can provide a dockerfile to reproduce. Essentially, run

    docker run --rm -it fedora:rawhide bash

It would be a good idea to run full doctest selftest suite, afterwards. Or maybe right now. I'll do that.

**Comment by jiridanek** [comment]
```
(gdb) bt full
#0  doctest::detail::Expression_lhs<int&>::operator==<int> (this=0x7fff717e6f10, rhs=<optimized out>, rhs=<optimized out>) at /main/qpid-dispatch/tests/c_unittests/doctest.h:1238
        res = <optimized out>
#1  0x00000000004218d8 in _DOCTEST_ANON_FUNC_2 () at /main/qpid-dispatch/tests/c_unittests/doctest.h:794
        _DOCTEST_RB = {<doctest::AssertData> = {m_test_case = 0x1210d50, m_at = doctest::assertType::DT_CHECK, m_file = 0x426c80 "/main/qpid-dispatch/tests/c_unittests/test_amqp.cpp", m_line = 28, m_expr = 0x426c6f "(*a) == 5", 
            m_failed = true, m_threw = false, m_exception = {static len = 24, static last = 23, {buf = "\000o~q\377\177\000\000\354\210\177q\377\177\000\000k\200X`\000\000\000\027", data = {ptr = 0x7fff717e6f00 "", size = 1904183532, 
                  capacity = 32767}}}, m_decomp = {static len = 24, static last = 23, {buf = "\000\177\036\"\000\000\000\000\230s~q\377\177\000\000\000\000\000\000\000\000\000\027", data = {
                  ptr = 0x221e7f00 <error: Cannot access memory at address 0x221e7f00>, size = 1904112536, capacity = 32767}}}, m_threw_as = false, m_exception_type = 0x4258df "", m_exception_string = 0x4258df ""}, <No data fields>}
        a = 0x0
#2  0x000000000041db7b in doctest::Context::run (this=<optimized out>) at /main/qpid-dispatch/tests/c_unittests/doctest.h:6486
        fatalConditionHandler = {static isSet = true, static oldSigActions = {{__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 
                  140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 4351856}}, sa_flags = 0, sa_restorer = 0x0}, {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 
                  140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 4351856}}, sa_flags = 0, sa_restorer = 0x0}, {__sigaction_handler = {
                sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 
                  4351856}}, sa_flags = 0, sa_restorer = 0x0}, {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 
                  140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 4351856}}, sa_flags = 0, sa_restorer = 0x0}, {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 
                  140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 4351856}}, sa_flags = 0, sa_restorer = 0x0}, {__sigaction_handler = {
                sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 30, 140735097499520, 0, 140735097499568, 0, 18943312, 140735097499552, 140735097571564, 1616412779, 572424007, 140735097500568, 0, 18944240, 4256238, 
                  4351856}}, sa_flags = 0, sa_restorer = 0x0}}, static oldSigStack = {ss_sp = 0x0, ss_flags = 2, ss_size = 0}, static altStackSize = 32768, static altStackMem = 0x1212340 ""}
        run_test = true
        tc = @0x1210d50: {<doctest::TestCaseData> = {m_file = {static len = 24, static last = 23, {buf = "\340\r!\001\000\000\000\000\063\000\000\000\064\000\000\000\000\000\000\000\000\000\000\200", data = {
                  ptr = 0x1210de0 "/main/qpid-dispatch/tests/c_unittests/test_amqp.cpp", size = 51, capacity = 52}}}, m_line = 26, m_name = 0x4258df "", m_test_suite = 0x4258df "", m_description = 0x0, m_skip = false, 
            m_no_breaks = false, m_no_output = false, m_may_fail = false, m_should_fail = false, m_expected_failures = 0, m_timeout = 0}, m_test = 0x421870 <_DOCTEST_ANON_FUNC_2()>, m_type = 0x4258df "", m_template_id = -1, 
          m_full_name = {static len = 24, static last = 23, {buf = "\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\001\000\000\000\000\000\000\027", data = {ptr = 0x0, size = 4, capacity = 0}}}}
        skip_me = <optimized out>
        curr = <optimized out>
        __for_range = <optimized out>
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_begin = 
Python Exception <class 'gdb.error'> value has been optimized out: 
        __for_end = 
        old_cs = <optimized out>
        fstr = <incomplete type>
        cleanup_and_return = {__fstr = <optimized out>, __old_cs = <optimized out>, __this = <optimized out>}
        testArray = std::vector of length 4, capacity 4 = {0x1210d50, 0x1210e40, 0x1210f30, 0x1211020}
        testSuitesPassingFilt = std::set with 0 elements
        query_mode = <optimized out>
        queryResults = std::vector of length 0, capacity 0
        DOCTEST_FIX_FOR_MACOS_LIBCPP_IOSFWD_STRING_LINK_ERRORS = {<No data fields>}
#3  0x000000000040b0cf in main (argc=<optimized out>, argv=<optimized out>) at /main/qpid-dispatch/tests/c_unittests/doctest.h:6571
No locals.
```

**Comment by onqtam** [comment]
@jiridanek seems about right :)

**Comment by jiridanek** [comment]
Uh, yeah. I did not stop to think what I should actually expect to see. Test crashed but doctest finished and printed summary, so all well and good.

I am looking how to run test/examples. The GitHub Actions syntax is not very helpful when I want to run things in the terminal...
Thankfully cmake; make; ctest seems to work, without me setting anything else. I guess it means I just won't be turning on sanitizers.

```
[...]
132/135 Test #132: same_tests_multiple_configurations_junit ...   Passed    0.02 sec
        Start 133: playground
133/135 Test #133: playground .................................   Passed    0.02 sec
        Start 134: playground_xml
134/135 Test #134: playground_xml .............................   Passed    0.02 sec
        Start 135: playground_junit
135/135 Test #135: playground_junit ...........................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 135

Total Test time (real) =   3.29 sec
```

**Comment by dankamongmen** [comment]
> It would be goot to test with a crashing example as well (to test the signal handler and alt stack) - something like:
> 
> ```c++
> TEST_CASE("") {
>     int* a = nullptr;
>     CHECK((*a) == 5);
> }
> ```

IMHO this stands a good chance of being elided by the compiler -- a `raise(SIGSEGV)` is a better route, at least on UNIX
