### ISSUE TITLE
CAPTURE of structured binding element no longer works

### ISSUE THREAD

**Issue by u3shit** [onqtam/doctest#279]
## Description
Take a look at the example below where I capture a variable from a structured binding. With 2.3.3 and before it worked fine, with 2.3.4 I receive an error like this:
```
foo.cpp:8:11: error: reference to local binding 'a' declared in enclosing function '_DOCTEST_ANON_FUNC_6'
  CAPTURE(a);
          ^
./doctest/doctest.h:2480:17: note: expanded from macro 'CAPTURE'
#define CAPTURE DOCTEST_CAPTURE
                ^
foo.cpp:7:9: note: 'a' declared here
  auto [a,b] = x;
        ^
1 error generated.
```
It looks like it was broken in 5e493d3f54eb389e3788ef431fba580d6bf6b141

### Steps to reproduce
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("x")
{
  int x[2] = {1,2};
  auto [a,b] = x;
  CAPTURE(a);
}
```
Compile it with `clang++ -std=c++17`. It also fails if I use an std::pair/tuple instead of an array.

### Extra information
* doctest version: **v2.3.4**
* Operating System: **Gentoo Linux amd64**
* Compiler+version: **clang 8.0.1 (both with libc++ and gcc's libstdc++)**

**Comment by onqtam** [comment]
Here is what the new INFO() looks like behind the curtains:

```c++
#include <iostream>

int main() {
    int x[2] = {1, 2};
    auto [a, b] = x;

    auto lambda_name = [&]() {
        std::cout << a << std::endl;
    };

    lambda_name();
}
```

This works with GCC 8.1 and fails with clang 6... and also with clang 8. I suspect it's a clang bug - this seems like normal C++ which I would expect to work. I haven't tested with MSVC but I suspect that it works there too.

**Comment by onqtam** [comment]
```INFO()``` relies on a ```[&]``` capture lambda underneath and the problem you've hit is this: https://stackoverflow.com/questions/46114214

........ This works with GCC but fails with clang (haven't tested MSVC).

You could work it around by making a separate ```auto& name = a;``` for now and ```CAPTURE(name);``` and hopefully the C++ 20/23 standard figures out what to do in this case.

**Comment by u3shit** [comment]
The funny thing is, I already had a macro for that workaround you suggested because of the rvalue limitation... looks like I no longer need it for rvalues, but now I need structured bindings. Am I the only one who feels c++ standards got buggier recently?
I haven't looked at the implementation, but wouldn't the initializer capture workaround work here? Like `[a=&a]() { return *a; }`

**Comment by onqtam** [comment]
it won't work in the following cases:

- ```INFO("aaa" << var1 << var2);```
- ```INFO("str");```

I don't know what the user will be capturing so the capture has to be ```[&]```... I can't generate a proper capture at compile time with macros from whatever the user has passed. Hopefully this will get fixed nicely in the future. Btw I really dislike C++ since I explored Nim and will even be giving a talk how it should replace it at code::dive 2019 :)

**Comment by onqtam** [comment]
releasing 2.3.5

**Comment by gitsbi** [comment]
This is not a bug in a compiler (nor in the standard), but a deliberate decision. The standard says structured bindings are no variables, and thus cannot be captured. (See the discussion [here](https://stackoverflow.com/q/46114214/140719) with relevant links.)
