### PR TITLE
linux: always include signal.h

### LINKED ISSUE #473: Can't compile with glibc master (future 2.34): SIGSTKSZ is no longer a constant
Hi,

I am trying to compile ccache (which embeds doctest as a third part library), using current glibc trunk (future glibc 2.34 to be released in 6 months). It fails with this error:

```
/workdir/src/ccache-4.2/src/third_party/doctest.h:4189:47: error: size of array 'altStackMem' is not an integral constant-expression
 4189 |         static char             altStackMem[4 * SIGSTKSZ];
```

Indeed if you look in latest NEWS file from glibc https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD:

```
  * Add _SC_MINSIGSTKSZ and _SC_SIGSTKSZ.  When _SC_SIGSTKSZ_SOURCE or
     _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ are no longer
     constant on Linux.  MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ)
     and SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ).
```

So would it be possible to update a bit the code to no longer rely on SIGSTKSZ being a constant ?

Cheers,
Romain

### PR DESCRIPTION
**Pull request by dankamongmen**
Taken against `dev`

## Description
Linux needs to always include `signal.h`, due to use of `SIGSTKSZ` independently of breakpoint mechanism.

## GitHub Issues
Closes #473

### CODE REVIEW

**Comment by dankamongmen** [comment]
wait, we're still seeing a failure on fedora: https://kojipkgs.fedoraproject.org//work/tasks/512/62220512/build.log

**Comment by dankamongmen** [comment]
ok yeah, this has been redefined as `sysconf(_SC_SIGSTKSZ)`, which isn't a constant, and thus won't fly in the `static char[]`. hrmm. i'm guessing a major point of the `static char` is so that it's preallocated at load time?

**Comment by onqtam** [comment]
> i'm guessing a major point of the `static char` is so that it's preallocated at load time?

Yeah, that's the point... perhaps I should just stick a raw integer in there :|

**Comment by Romain-Geissler-1A** [comment]
Hi,

I am not sure using an hardcoded signal stack size is the best idea, has the needed stack is growing constantly as new x86 processor do have more registers to save at each generation (and this make it quite error prone for other architecture). I would rather continue to use SIGSTKSZ but using dynamic malloc allocation instead of static char array.

Cheers,
Romain

**Comment by dankamongmen** [comment]
> I am not sure using an hardcoded signal stack size is the best idea, has the needed stack is growing constantly as new x86 processor do have more registers to save at each generation (and this make it quite error prone for other architecture). I would rather continue to use SIGSTKSZ but using dynamic malloc allocation instead of static char array.

Certainly a reasonable stance as well. The main reason I didn't want to go this way was the hope that a static area has no chance of being returned to the OS by a wayward heap interaction -- the exact kind of interaction which might provoke a fatal signal in the first place.

**Comment by onqtam** [comment]
I'll wait to see the answer of [my comment](https://github.com/onqtam/doctest/issues/473#issuecomment-803595472) and fix this issue

**Comment by onqtam** [comment]
I'm closing this PR as I've already pushed a fix for issue #473 - https://github.com/onqtam/doctest/commit/8ee91f37ba27397ef5eeedd2e542a4aaaa33ddc1
