### ISSUE TITLE
Using `DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES` does not compile using g++ 6.3.0

### ISSUE THREAD

**Issue by FSund** [onqtam/doctest#89]
## Description
A combination of `DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN`, and `DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES` doesn't compile on g++ 6.3.0. It compiles fine without `DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES`.

### Steps to reproduce
    #include <iostream>

    using namespace std;

    #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
    #define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
    #include "doctest.h"

    int factorial(int number)
    {
        return number <= 1 ? number : factorial(number - 1) * number;
    }

    TEST_CASE("testing the factorial function")
    {
        CHECK(factorial(1) == 1);
        CHECK(factorial(2) == 2);
        CHECK(factorial(3) == 6);
        CHECK(factorial(10) == 3628800);
    }

Compiled using `g++ -Wall main.cpp -o main` using g++ version 6.3.0 gives the error

    main.cpp:15:10: error: expected constructor, destructor, or type conversion before ‘(’ token
     TEST_CASE("testing the factorial function")
              ^

### Extra information

* doctest version: **v1.2.2**
* Operating System: **Debian 9 Stretch**
* Compiler+version: **g++ 6.3.0**

**Comment by onqtam** [comment]
Well ```TEST_CASE``` is a short macro name - so using ```DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES``` will disable it and only ```DOCTEST_TEST_CASE``` will remain usable.

**Comment by FSund** [comment]
Quite the response time here!

I did not think of that option, but should if course have realized it. I wish the error messages were better.
